config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :order_products

  resources :products do
    delete '/order_products', to: 'order_products#destroy'
  end
  devise_for :users
  # devise_for :users :controllers => { sessions: 'users/sessions'}
  resource :cart, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/views/layouts/_cart.html.erb
<div class="col-lg-6">
  <div class="well sidebar-nav">
    <h3>Cart</h3>
    <ul class="nav nav-list">
      <li class="nav-header">Here are all your items</li>
      <% if @order_products.any? %>
        <% @order_products.each do |order_product| %>
        <!-- pass order_product.id in id in the delete params -->
          <p><%= order_product.product.name %> | <%= link_to "Delete", order_product_path(:id => order_product.id), :data => {:confirm => "You sure?", :method => "delete"} %></p>
          <p> <%= number_to_currency order_product.product.price %> x <%= order_product.quantity %> = Total Price: <%= number_to_currency (order_product.product.price * order_product.quantity) %></p>
        <% end %>
        <p>Your Total: <%= number_to_currency current_order.total_price %></p>
      <% else %>
        <p>Your shopping cart is empty.</p>
      <% end %>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "RailsShop", root_path, class:"navbar navbar-brand" %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav col-md-6">
        <li><%= link_to "All Products", products_path %></li>
        <li><%= link_to "Cart", cart_path  %></li>
        <li><%= link_to "Link3", "/path3"  %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right col-md-1">
        <li class='no-padding'><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-xs btn-danger' %></li>
      </ul>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RailsShop" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>